#!/bin/bash

arnold_version=$(cat $IJ_LOCAL_REPO/etc/arnold_version)
aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)

if [[ $IJ_OS == "mac" ]]; 
then 
    export arnold_root=~/htoa
    export ocio_root=/mnt/luma_h/SITE/ocio
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export arnold_root=/opt/htoa
    export ocio_root=/opt/OpenColorIO-Configs
fi

export OCIO=$ocio_root/$aces_version/config.ocio

# ARNOLD
HTOA=$arnold_root/$arnold_version/$arnold_version
export PATH=$HTOA/scripts/bin:$PATH
export ADSKFLEX_LICENSE_FILE=2080@192.168.35.28
