#!/bin/bash

aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)
if [[ $IJ_TESTING == "1" ]]; 
then 
    arnold_version=$(cat $IJ_LOCAL_REPO/etc/arnold_version_testing)
elif [[ $IJ_TESTING == "2" ]];
then
    arnold_version=0
else
    arnold_version=$(cat $IJ_LOCAL_REPO/etc/arnold_version)
fi

if [[ $IJ_OS == "mac" ]]; 
then 
    export arnold_root=~/htoa
    export ocio_root=/mnt/luma_h/SITE/ocio
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export arnold_root=/opt/htoa
    export ocio_root=/opt/OpenColorIO-Configs
fi

export OCIO=$ocio_root/$aces_version/config.ocio

# ARNOLD
HTOA=$arnold_root/$arnold_version/$arnold_version
export PATH=$HTOA/scripts/bin:$PATH
case $(hostname -s) in
  luma-film-borg*) 
    export ADSKFLEX_LICENSE_FILE=2080@192.168.35.28;
    ;;
  *) 
    echo;
    ;;
esac
