#!/bin/bash

aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)

if [[ $IJ_TESTING == "1" ]]; 
then 
    blender_version=$(cat $IJ_LOCAL_REPO/etc/blender_version_testing)
else
    blender_version=$(cat $IJ_LOCAL_REPO/etc/blender_version)
fi

if [[ $IJ_OS == "mac" ]]; 
then 
    export ocio_root=/mnt/luma_h/SITE/ocio
    export blender_root=/Applications/Blender/$blender_version/Blender.app/Contents/MacOS;
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export ocio_root=/opt/OpenColorIO-Configs
    export blender_root=/opt/blender/$blender_version;
fi

export OCIO=$ocio_root/$aces_version/config.ocio
