#!/bin/bash

aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)
if [[ $IJ_TESTING == "1" ]]; 
then 
    mari_version=$(cat $IJ_LOCAL_REPO/etc/mari_version_testing)
else
    mari_version=$(cat $IJ_LOCAL_REPO/etc/mari_version)
fi

if [[ $IJ_OS == "mac" ]]; 
then 
    # export mari_root=/Applications/Mari/$mari_version/mari$mari_version.app/Contents/MacOS
    # export OCIO=/opt/OpenColorIO-Configs/$aces_version/config.ocio
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export mari_root=/opt/mari/$mari_version
    export OCIO=/opt/OpenColorIO-Configs/$aces_version/config.ocio
fi
