#!/bin/bash

export LC_ALL=C
unset LANGUAGE

unset OCIO

if [[ $IJ_OS == "mac" ]]; 
then 
    export MAYA_LOCATION=/Applications/Autodesk/maya2016.5/Maya.app/Contents

    export RMANTREE=/Applications/Pixar/RenderManProServer-21.8
    export RFMTREE=/Applications/Pixar/RenderManForMaya-21.8-maya2016.5
    export MAYA_MODULE_PATH=/opt/pixar/RenderManForMaya-21.8-maya2016.5:$MAYA_MODULE_PATH
    
    # MGEAR
    export MAYA_MODULE_PATH=~/Library/Preferences/Autodesk/maya/modules:$MAYA_MODULE_PATH
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export MAYA_LOCATION=/usr/autodesk/maya2016.5

    export RMANTREE=/opt/pixar/RenderManProServer-21.8
    export RFMTREE=/opt/pixar/RenderManForMaya-21.8-maya2016.5
    export MAYA_MODULE_PATH=/opt/pixar/RenderManForMaya-21.8-maya2016.5:$MAYA_MODULE_PATH

    # MGEAR
    export MAYA_MODULE_PATH=/mnt/luma_i/_tools/maya/mgear/release:$MAYA_MODULE_PATH
fi

export PIXAR_LICENSE_FILE=9010@192.168.35.28
export RFM_DO_NOT_CREATE_MODULE_FILE=1
export MAYA_SHELF_PATH=/job/common/maya/shelves/
export MAYA_DISABLE_CIP=1
export MAYA_DISABLE_CER=1

# Some FC stuff
export PATH=/job/insidejob_movie/common/bin:$MAYA_LOCATION/bin:$PATH
export PYTHONPATH=/job/common/maya/scripts:$PYTHONPATH
