#!/bin/bash

aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)
natron_version=$(cat $IJ_LOCAL_REPO/etc/natron_version)

if [[ $IJ_OS == "mac" ]]; 
then 
    echo "NOPE"
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export natron_root=/opt/natron/$natron_version
    export OCIO=/opt/OpenColorIO-Configs/$aces_version/config.ocio
fi
