#!/bin/bash

aces_version=$(cat $IJ_LOCAL_REPO/etc/aces_version)
if [[ $IJ_TESTING == "1" ]]; 
then 
    nuke_version=$(cat $IJ_LOCAL_REPO/etc/nuke_version_testing)
    nuke_command="Nuke12.2"
else
    nuke_version=$(cat $IJ_LOCAL_REPO/etc/nuke_version)
    nuke_command="Nuke12.0"
fi

if [[ $IJ_OS == "mac" ]]; 
then 
    export nuke_root=/Applications/Nuke$nuke_version/Nuke$nuke_version.app/Contents/MacOS
    unset NUKE_PATH
    export NUKE_PATH=/opt/nuke_plugs:$NUKE_PATH
    export NUKE_PATH=/opt/nuke_plugs/Cryptomatte/nuke:$NUKE_PATH
    export NUKE_PATH=/opt/nuke_plugs/ffmpeg_write:$NUKE_PATH
    export OCIO=/opt/OpenColorIO-Configs/$aces_version/config.ocio
fi
if [[ $IJ_OS == "lin" ]]; 
then 
    export nuke_root=/opt/Nuke$nuke_version
    export NUKE_PATH=/opt/nuke_plugs:$NUKE_PATH
    export NUKE_PATH=/opt/nuke_plugs/Cryptomatte/nuke:$NUKE_PATH
    export NUKE_PATH=/opt/nuke_plugs/ffmpeg_write:$NUKE_PATH
    export OCIO=/opt/OpenColorIO-Configs/$aces_version/config.ocio
    export OPTICAL_FLARES_PATH=/opt/nuke_plugs/OpticalFlares
    export OPTICAL_FLARES_PRESET_PATH=/opt/nuke_plugs/OpticalFlares/Textures-And-Presets
    export OPTICAL_FLARES_DISPLAY_NAME=:1
    export OPTICAL_FLARES_LICENSE_PATH=192.168.35.28
    export OPTICAL_FLARES_LICENSE_SERVER_IP=192.168.35.28
fi

export peregrinel_LICENSE=5053@192.168.35.1
